[package]
name = "aptos-api-tester"
description = "Aptos developer API tester"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
aptos-sdk = { workspace = true }
aptos-rest-client = { workspace = true }
aptos-api-types = { workspace = true }
aptos-types = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }
once_cell = { workspace = true }
rand = { workspace = true }
anyhow = { workspace = true }
aptos-cached-packages = { workspace = true }
