[package]
name = "MemberGroup"
version = "0.0.1"

[dependencies]
AptosFramework = { local = "../../framework/aptos-framework" }
AptosStdlib = { local = "../../framework/aptos-stdlib" }

[addresses]
dport_std = "_"
